#!/bin/bash
# a 'unzip -p some-jar-file.jar META-INF/MANIFEST.MF' wrapper
# created by zhouwei on 2016-2-3

if (($# < 1)); then
    echo "Usage: catmf jarfile.jar"
    exit 1
fi

for file in "$@"
do
    unzip -p $file META-INF/MANIFEST.MF
done

exit 0
