#!/bin/bash
# escape double quotes, replace " into \"
# read from stdin, and write into stdout
# created by zhouwei on 2017-02-22

while read line
do
    echo "$line" | sed 's/"/\\"/g'
    echo ""
done
