#!/bin/bash
# escape double-quotes: replace " to \"
# read from stdin, and write to stdout
# usage: escape
# created by zhouwei on 2017-02-22

while read line
do
    echo "$line" | sed 's/"/\\"/g'
    echo ""
done
