#!/bin/bash
# a command wrapper script: find . -type f -exec grep --color=auto -H -n "$key" {} \;
# created by zhouwei on 2015-9-10

if (($# != 1)) ; then
    echo "Usage: ff key"
    exit 1
fi

key="$1"

find . -type f -exec grep --color=auto -H -n "$key" {} \;

exit 0
