#!/bin/bash
# a command wrapper script: find . -type f -exec grep --color=auto -H $key {} \;
# or: find . -type f -exec grep -l $key {} \;
# created by zhouwei on 2015-9-10

if (($# < 1)) ; then
    echo "Usage: ff key [-l]"
    exit 1
fi

key="$1"
list_flag="$2"

if [ "${list_flag}" = "-l" ]; then
    find . -type f -exec grep -l "$key" {} \;
else
    find . -type f -exec grep --color=auto -H "$key" {} \;
fi

exit 0
