#!/bin/bash
# linux performance analysis tool
# used in the first 60 seconds after login to a server with a performance issue
# inspired by http://techblog.netflix.com/2015/11/linux-performance-analysis-in-60s.html
# created by zhouwei on 2016-6-22

print_line() {
    echo ""
    echo "=================================================================================="
    echo ""
}

# stats start
outfile="perf_stats_$(date '+%Y-%m-%d_%H:%M:%S')"
exec 3>&1
exec 1>$outfile

# print file header
echo "linux performance analysis statistics"
echo "date: $(date '+%Y-%m-%d %H:%M:%S')"
print_line

# uptime
echo "uptime:"
uptime
print_line

# dmesg and /var/log/messages
echo "dmesg:"
dmesg | tail -20
if [ -f /var/log/messages ]; then
    echo ""
    echo "/var/log/messages:"
    tail -20 /var/log/messages
fi
print_line

# memory and disk usages
echo "memory usage:"
free -m
echo ""
echo "disk usage:"
df -h
print_line

# 
print_line

#
print_line

#
print_line

#
print_line

# 
print_line

# the end
exec 1>&3
exec 3>&-
echo "performance statistics finished!"
echo "outfile: $(pwd)/$outfile"

exit 0
