#!/bin/bash
# a 'tar jcvf' wrapper
# created by zhouwei on 2016-2-3

if (($# < 2)) ; then
    echo "Usage: tarc filename_prefix files..."
    exit 1
fi

filename_prefix=$1
shift
tar jcvf "${filename_prefix}.tar.bz2" "$@"
if (($? != 0)); then
    rm -f "${filename_prefix}.tar.bz2" >&/dev/null
    exit 1
fi

exit 0
