#!/bin/bash
# a 'tar cf' wrapper
# created by zhouwei on 2016-2-3

if (($# < 2)) ; then
    echo "Usage: tarc filename_prefix files..."
    exit 1
fi

filename_prefix=$1
shift
tar cf "${filename_prefix}.tar" "$@"
if (($? != 0)); then
    rm -f "${filename_prefix}.tar" >&/dev/null
    exit 1
fi

exit 0
